Controllers/PatientController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PMSMVC.Models;
using Microsoft.AspNetCore.Http;



using System;

using System.Collections.Generic;

using System.Linq;

using System.Net;

using System.Net.Http;

using System.Net.Http.Headers;

using System.Text;

using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PMSMVC.Controllers
{
    public class PatientController : Controller
    {
        string Baseurl = "http://localhost:61003/";
        public IActionResult PatientDashBoard()
        {
            return View();
        }

     
       

        [HttpGet]
        public async Task<IActionResult> Register()
        {
            List<BloodGroups> PInfo = new List<BloodGroups>();
            if (HttpContext.Session.GetString("Jwtoken") == null)
            {
                return RedirectToAction("PatientLogin", "Patient");
            }
            using (var client = new HttpClient())
            {
                //Passing service base url
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                //Define request data format
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Jwtoken"));
                //Sending request to find web api REST service resource GetAllEmployees using HttpClient
                HttpResponseMessage Res = await client.GetAsync("api/BloodGroups");
                //Checking the response is successful or not which is sent using HttpClient
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api
                    var Response = Res.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list
                    PInfo = JsonConvert.DeserializeObject<List<BloodGroups>>(Response);
                }
                ViewBag.BloodGroupId = new SelectList(PInfo, "BloodGroupId", "BloodGroup");
                return View();
            }
        }

     

        [HttpPost]
        public async Task<IActionResult> Register(Patient patient)
        {
           
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(patient), Encoding.UTF8, "application/json");
                string endpoint = Baseurl + "api/Patient/AddPatient"; 
                using (var Response = await client.PostAsync(endpoint, content))
                {
                    if (Response.StatusCode == HttpStatusCode.OK)
                    {
                        TempData["Patient"] = JsonConvert.SerializeObject(patient);
                        ViewBag.Message = "Registration Successful";
                        return RedirectToAction("RegistrationSuccessful");
                    }
                    else
                    {
                        ModelState.Clear();
                        ModelState.AddModelError(string.Empty, "Could not register Patient");
                        return View();
                    }
                }
            }
        }

        public IActionResult RegistrationSuccessful()
        {
            return View();
        }

        [HttpGet]

        public async Task<IActionResult> BookAppointment()
        {
            List<Departments> PInfo = new List<Departments>();
            if (HttpContext.Session.GetString("Jwtoken") == null)
            {
                return RedirectToAction("PatientLogin", "Patient");
            }
            using (var client = new HttpClient())
            {
                //Passing service base url
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                //Define request data format
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Jwtoken"));
                //Sending request to find web api REST service resource GetAllEmployees using HttpClient
                HttpResponseMessage Res = await client.GetAsync("api/Departments");
                //Checking the response is successful or not which is sent using HttpClient
                if (Res.StatusCode == HttpStatusCode.OK)
                {
                    //Storing the response details recieved from web api
                    var Response = Res.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list
                    PInfo = JsonConvert.DeserializeObject<List<Departments>>(Response);
                }
                ViewBag.DepartmentId = new SelectList(PInfo, "DepartmentId", "DepartmentName");
                return View();
            }
        }


        [HttpGet]
        public async Task<IActionResult> GetHistory(string id)
        {
            List<Appointment> PInfo = new List<Appointment>();
            if (HttpContext.Session.GetString("Jwtoken") == null)
            {
                return RedirectToAction("PatientLogin", "Patient");
            }
            using (var client = new HttpClient())
            {
                //Passing service base url
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                //Define request data format
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Jwtoken"));
                //Sending request to find web api REST service resource GetAllEmployees using HttpClient
                HttpResponseMessage Res = await client.GetAsync("api/Patient/GetHistory/" + id);
                //Checking the response is successful or not which is sent using HttpClient
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api
                    var Response = Res.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list
                    PInfo = JsonConvert.DeserializeObject<List<Appointment>>(Response);
                }
                return View();
            }
        }






        [HttpGet]

        public async Task<IActionResult> GetDoctors()
        {
            List<Doctor> PInfo = new List<Doctor>();
            if (HttpContext.Session.GetString("Jwtoken") == null)
            {
                return RedirectToAction("PatientLogin", "Patient");
            }
            using (var client = new HttpClient())
            {
         
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
               
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Jwtoken"));
                HttpResponseMessage Res = await client.GetAsync("api/Patient/GetDoctors");
           
                if (Res.StatusCode == HttpStatusCode.OK)
                {
                  
                    var Response = Res.Content.ReadAsStringAsync().Result;
                  
                    PInfo = JsonConvert.DeserializeObject<List<Doctor>>(Response);
                }
               
                return View(PInfo);
            }
        }


        [HttpPost]
        public async Task<IActionResult> BookAppointment(Appointment appointment)
        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(appointment), Encoding.UTF8, "application/json");
                string endpoint = Baseurl + "api/Appointments";
                using (var Res = await client.PostAsync(endpoint, content))
                {

                    if (Res.IsSuccessStatusCode)
                    {
                        TempData["Appointment"] = JsonConvert.SerializeObject(appointment);
                        return RedirectToAction("PatientDashBoard");
                    }
                    else
                    {
                        ModelState.Clear();
                        ModelState.AddModelError(string.Empty, "Could not Book Appointment.");
                        return View();
                    }
                }
            }

        }

        public IActionResult PatientLogout()
        {
            HttpContext.Session.Remove("Jwtoken");
            return RedirectToAction("PatientLogin", "Patient");

        }


        [HttpGet]
        public IActionResult PatientLogin()
        {
            
            return View();
        }



        [HttpPost]

        public async Task<IActionResult> PatientLogin(PatientLogin patient)

        {

            using (HttpClient client = new HttpClient())

            {

                StringContent content = new StringContent(JsonConvert.SerializeObject(patient), Encoding.UTF8, "application/json");

                string endpoint = Baseurl + "api/Patient/Login";
                using (var Response = await client.PostAsync(endpoint, content))

                {

                    string token = await Response.Content.ReadAsStringAsync();

                    if (token == "User not found")

                    {

Controllers/PatientsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using PMSMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace PMSMVC.Controllers
{
    public class PatientsController : Controller
    {
        string Baseurl1 = "http://localhost:61003/";

        [HttpGet]

        public async Task<ActionResult> Index()
        {
            List<Appointment> PInfo = new List<Appointment>();
           
            using (var client = new HttpClient())
            {
                //Passing service base url
                client.BaseAddress = new Uri(Baseurl1);
                client.DefaultRequestHeaders.Clear();
                //Define request data format
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                //Sending request to find web api REST service resource GetAllEmployees using HttpClient
                HttpResponseMessage Res = await client.GetAsync("api/Appointments/Get");
                //Checking the response is successful or not which is sent using HttpClient
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api
                    var Response = Res.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list
                    PInfo = JsonConvert.DeserializeObject<List<Appointment>>(Response);
                }
                //returning the employee list to view
                return View(PInfo);
            }
        }




        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            Patient PInfo = new Patient();
            

            using (var client = new HttpClient())
            {
                //Passing service base url
                client.BaseAddress = new Uri(Baseurl1);
                client.DefaultRequestHeaders.Clear();

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("api/HospitalEmp/PatientById/" + id);



                if (Res.IsSuccessStatusCode)
                {

                    var Response = Res.Content.ReadAsStringAsync().Result;

                    PInfo = JsonConvert.DeserializeObject<Patient>(Response);

                }
                return View(PInfo);
            }

        }



        [HttpPost]
        public async Task<IActionResult> Edit(string id, Doctor doctor)
        {


            using (HttpClient client = new HttpClient())
            {


                StringContent content = new StringContent(JsonConvert.SerializeObject(doctor), Encoding.UTF8, "application/json");
                string endpoint = this.Baseurl1 + "api/HospitalEmp/PutDoctor/" + id;
                using (var Response = await client.PutAsync(endpoint, content))
                {

                    if (Response.IsSuccessStatusCode)
                    {
                        TempData["Doctor"] = JsonConvert.SerializeObject(doctor);

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.Clear();
                        ModelState.AddModelError(string.Empty, "Could not update doctor");
                        return View();
                    }


                }
            }
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            Appointment appointment  = new Appointment();
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(appointment), Encoding.UTF8, "application/json");
                string endpoint = this.Baseurl1 + "api/Appointments/" + id;
                using (var Response = await client.PostAsync(endpoint, content))
                {
                    if (Response.IsSuccessStatusCode)
                    {
                        TempData["Appointment"] = JsonConvert.SerializeObject(appointment);

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.Clear();
                        ModelState.AddModelError(string.Empty, "Could not delete doctor");
                        return View();
                    }
                }
            }
        }




        [HttpGet]

        public async Task<IActionResult> BookAppointment()
        {
            List<Departments> PInfo = new List<Departments>();
          
            using (var client = new HttpClient())
            {
                //Passing service base url
                client.BaseAddress = new Uri(Baseurl1);
                client.DefaultRequestHeaders.Clear();
                //Define request data format
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                //Sending request to find web api REST service resource GetAllEmployees using HttpClient
                HttpResponseMessage Res = await client.GetAsync("api/Departments");
                //Checking the response is successful or not which is sent using HttpClient
                if (Res.StatusCode == HttpStatusCode.OK)
                {
                    //Storing the response details recieved from web api
                    var Response = Res.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the Employee list
                    PInfo = JsonConvert.DeserializeObject<List<Departments>>(Response);
                }
                ViewBag.DepartmentId = new SelectList(PInfo, "DepartmentId", "DepartmentName");
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> BookAppointment(Appointment appointment)
        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(appointment), Encoding.UTF8, "application/json");
                string endpoint = Baseurl1 + "api/Appointments";
                using (var Res = await client.PostAsync(endpoint, content))
                {

                    if (Res.IsSuccessStatusCode)
                    {
                        TempData["Appointment"] = JsonConvert.SerializeObject(appointment);
                        return RedirectToAction("PatientDashBoard");
                    }
                    else
                    {
                        ModelState.Clear();
                        ModelState.AddModelError(string.Empty, "Could not Book Appointment.");
                        return View();
                    }
                }
            }

        }

       







       

    }
}

Views/Patients/BookAppointment.cshtml
@model PMSMVC.Models.Appointment

@{
    ViewData["Title"] = "BookAppointment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>BookAppointment</h1>

<h4>Appointment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="BookAppointment">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AppointmentId" class="control-label"></label>
                <input asp-for="AppointmentId" class="form-control" />
                <span asp-validation-for="AppointmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PatientId" class="control-label"></label>
                <input asp-for="PatientId" class="form-control" />
                <span asp-validation-for="PatientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId"></select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorId" class="control-label"></label>
                <input asp-for="DoctorId" class="form-control" />
                <span asp-validation-for="DoctorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppointmentDate" class="control-label"></label>
                <input asp-for="AppointmentDate" class="form-control" />
                <span asp-validation-for="AppointmentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConsultationFees" class="control-label"></label>
                <input asp-for="ConsultationFees" class="form-control" />
                <span asp-validation-for="ConsultationFees" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Patients/Delete.cshtml
@model PMSMVC.Models.Appointment

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Appointment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppointmentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppointmentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatientId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoctorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppointmentDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppointmentDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConsultationFees)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConsultationFees)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-controller="Patients">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Patients/Index.cshtml
@model IEnumerable<PMSMVC.Models.Appointment>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AppointmentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PatientId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoctorId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppointmentDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ConsultationFees)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AppointmentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PatientId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppointmentDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ConsultationFees)
            </td>
            <td>
                @Html.ActionLink("Edit", "Patients", new { id=item.AppointmentId }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.AppointmentId })
            </td>
        </tr>
}
    </tbody>
</table>